### ISSUE TITLE
no speed increase

### ISSUE THREAD

**Issue by zhangliye** [JuliaParallel/Dagger.jl#71] opened 2018-01-18 16:56 UTC
I tested the following code in two situations:
(1) Run from Juno
When i run the code in Juno, the code should be run with “addprocs()” before “using Dagger” first. There is no speed increase for the first run. Then, delete the code “addprocs()”, run the code again. There is speed increase.
(2) Run from the command
When I run the code with/without “addprocs()” from the command. There is no speed increase.

Run on windows 7, 64 Bit, with 4 CPU cores,  Julia0.61, Dagger v0.5.1 

```
using Dagger     # comment this code after the first run
@show workers()

@everywhere function f1(x)
    sleep(1)
    rand()+x
end

vs = [rand(Int) for i in 1:10];
cks = Any[]
for v in vs
    push!(cks, delayed(f1)(v))
end

@everywhere combine(x...) = nothing
c = delayed(combine)(cks...)
f1(1)

## runnint time with Dagger
@time compute(c)
```

**Comment by visr** [comment] 2020-02-10 11:05
On julia 1.4-rc1 and Dagger master I cannot reproduce this. A 4 worker version runs in 1 second, a 1 worker version in 3 seconds.

You mention "is no speed increase for the first run". In the first run it is compiling a lot of code, so it is best to avoid using the first time in a benchmark. The first time indeed I also don't see a speedup, though it does become apparent it if I change the `sleep(1)` to `sleep(5)`.

**Comment by jpsamaroo** [comment] 2020-02-10 12:13
This also doesn't appear to be related to the known scheduling issues in #84, so I'm closing this. Thanks for testing this @visr !

**Closed by jpsamaroo** 2020-02-10 12:13 UTC
Labels: performance, scheduler
